### ISSUE TITLE
Welcome middleware

### ISSUE THREAD

**Issue by harikt** [slimphp/Slim-HttpCache#1]
Hey, 

Nice to see your cache middleware. I was looking at the code, and find it also suits Conduit and may be others which are PSR-7 framework.

Some questions / concerns : 

1 . I think the CacheProvider is mainly for Pimple . May be we can move that also to require-dev ?

As I am not so closely watching Slim, ( even I am watching) I may have missed whether you said of splitting the PSR-Http of Slim. Any plans of splitting to standalone component ?

Thank you

**Comment by codeguy** [comment]
I'd rather have a hard-dependency on Pimple since that is required to use the code in this repo. I'll separate the HTTP stuff into its own component soon :)

**Comment by harikt** [comment]
Thank you.

**Comment by harikt** [comment]
By the way even if its on require-dev pimple will be installed on Slim . But your preference :) .

**Comment by harikt** [comment]
Hi Josh, 

Was looking again ( working with https://github.com/slimphp/Slim/pull/1153 ), and was wondering whether it is good to document how to use `ETag`, `Cache-Control` with PSR-7 response than using a provider.

Or do you still believe cache provider is nice addition ?
