### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by sirber** [slimphp/Slim-HttpCache#17]
Response header:

Cache-Control:no-store, no-cache, must-revalidate
Cache-Control:public, max-age=86400
ETag:"default_css"

then the client asks it again, whitout the etag.

**Comment by 0x2c** [comment]
Can confirm does not cache and revalidates with every request.
Use header() instead.

**Comment by wony-zheng** [comment]
it is php native session make duplicate header, [see](http://help.slimframework.com/discussions/problems/935-duplicate-http-header). IMO, if you want control http cache finely, you should write another index.php

**Comment by akrabat** [comment]
Closed as this issue is very old. If the problem remains, please reopen with further details.
