### ISSUE TITLE
http cache method on controller methods

### ISSUE THREAD

**Issue by jaymoh** [slimphp/Slim-HttpCache#20]
Hi, Am trying to get the slim cache provider to work on controller methods but am not able to reach a solution. I have added the HTTP cache provider from composer following the steps from this [Slim Page](https://www.slimframework.com/docs/features/caching.html) and even added it through dependency injection. Then I have a method that needs to return a JSON response with cache expires to my client app. I have done the tests in Postman and am getting the "Slim application error" Here is my settup>>
`$app=new Slim\App();
$app->add(new \Slim\HttpCache\Cache('public', 86400));
//require dependencies
require './app/dependencies.php';
//require routes
require './app/routes.php';
$app->run();`

here is the dependencies file>>
` <?php
$container=$app->getContainer();
$container['cache'] = function () {
    return new \Slim\HttpCache\CacheProvider();
};
$container['UserController']=  function (){
return new UserController();
};
$container['SongsController']=  function (){
return new SongsController();
};
`

Here is part of  the routes file>>
`$app->get('/login', 'UserController:login');
$app->get('/songs/all[/{offset}]', 'SongsController:all');`

And finally the method in SongsController that should return the result with cache is this>>

`     public function all($request, $response, $args){
        $res=array();
        $uid=  $this->authToken();

        if ($uid){
            //proceed
            $body=$request->getQueryParams();
            $offset=isset($body['offset']) ? $body['offset'] : 0;
            $res['success']=1;
            $res['messages']="Songs retrieved";
            $res['uid']=$uid;
            $res['audios']=  $this->getAllAudios($offset);
        }else{
            $res['success']=3;
            $res['message']="Access denied! Please login to proceed";
        }         
            $response->withJson($res);

            $newResponse = $this->cache->withExpires($response, time() + 3600);
        return $newResponse;
    }`

**Comment by proclnas** [comment]
@jaymoh same here.
Solved?

**Comment by jaymoh** [comment]
@proclnas yes, I made changes to the second line in the code as follows
`$newResponse = $this->cache->withExpires($response->withJson($res), time() + 7200); `

Then I implemented the caching in my Android app (I was using Volley for network calls, it has cache classes). By the way: 
`// 7200  caches for 2 hours`

you can set with your time
