### ISSUE TITLE
Need to specify a target version for phpunit?

### ISSUE THREAD

**Issue by andybeak** [slimphp/Slim-HttpCache#22]
When Travis tests on php version 7 it installs a newer version of phpunit.

This results in the error `PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in /home/travis/build/slimphp/Slim-HttpCache/tests/CacheProviderTest.php on line 7` ([example](https://travis-ci.org/slimphp/Slim-HttpCache/jobs/254374189))

This happens because phpunit  version 6 released on 2017-02-03 is namespaced.  You will need to refactor things like \PHPUnit_Framework_TestCase to \PHPUnit\Framework\TestCase

**Comment by akrabat** [comment]
Fixed now I think.
