### ISSUE TITLE
Slim 4 compatibility

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim-HttpCache#31]
I made an attempt to make this Slim 4 compatible. Please check https://github.com/adriansuter/Slim-HttpCache/tree/patch-slim4

@l0gicgate I could make a PR against a new branch if you like.

README is not updated yet.

**Comment by l0gicgate** [comment]
Lol you're a legend dude. I wasn't expecting you to get to this so quickly. Thank you. Let me create the `1.0` branch so we can PR against it.

**Comment by l0gicgate** [comment]
Just created the `0.x` and `1.x` branches. Please PR against the `1.x`.

Thank you
