### ISSUE TITLE
Unbind the Service Provider from the main code

### ISSUE THREAD

**Issue by akrabat** [slimphp/Slim-HttpCache#7]
From https://github.com/slimphp/Slim/issues/1275#issuecomment-110006099:

> Can we stop coupling the ServiceProvider with the actual code for the package. I see this is becoming a pattern that others will follow. Now that we are using Container Interop, we shouldn't bind the actual package to the Pimple ServiceProviderInterface, we should create a separate class in each package to do this.

**Comment by silentworks** [comment]
Done.
